#basic code
node {
    stage('Build') {
        echo 'Building...'
    }
    stage('Test') {
        echo 'Testing...'
    }
    stage('Deploy') {
        echo 'Deploying...'
    }
}


#groovy support full programme condtions like below 
node {
    stage('Decide') {
        if (env.BRANCH_NAME == 'main') {
            stage('Deploy to Prod') {
                echo 'Deploying to production'
            }
        } else if (env.BRANCH_NAME.startsWith('feature')) {
            stage('Deploy to Dev') {
                echo 'Deploying to dev'
            }
        }
    }
}


#for loop condition

def services = ["auth", "payment", "orders"]

node {
    for (svc in services) {
        stage("Build ${svc}") {
            echo "Building ${svc}"
        }
    }
}



# with choice parameters 

node {

    // Correct way to define parameters in Scripted pipeline
    properties([
        parameters([
            choice(
                name: 'action',
                choices: ['apply', 'destroy'],
                description: 'Choose the Terraform action to perform'
            )
        ])
    ])

    stage('Preparation') {
        git branch: 'main', url: 'https://github.com/CloudTechDevOps/Terraform-0730am.git'
    }

    stage('Init') {
        dir('Day-1-Terraform-basic-config') {
            sh 'terraform init'
        }
    }

    stage('Plan') {
        dir('Day-1-Terraform-basic-config') {
            sh 'terraform plan'
        }
    }

    stage('Execute') {
        dir('Day-1-Terraform-basic-config') {
            sh "terraform ${params.action} -auto-approve"
        }
    }
}
